CREATE OR REPLACE NONEDITIONABLE TRIGGER new_custom_foreign_key
    BEFORE DELETE ON GROUPS
    FOR EACH ROW
    BEGIN
        EXECUTE IMMEDIATE 'DELETE FROM STUDENTS WHERE STUDENTS.group_id = '||:OLD.id;
    END;
